### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by n8fr8** [Tasssadar/multirom#10]
First, AMAZING work. I will be sending a bitcoin donation shortly for this incredible tool. 

My "issue" below is whether the system rw mode and no encryption support is impossible, or just hard?

"About security
In order to make multi-booting possible, MultiROM has to sacrifice some security measures. Firstly, on secondary Android ROMs, /system is not mounted read-only. While there are other things preventing malicious software from messing with /system, this might potentialy make it easier for such software to attack that system.
Next, MultiROM doesn't work with /data encryption. Not many people who use custom ROMs also use encryption anyway, so that isn't much of a concern."

**Comment by patcon** [comment]
> it simply isn't worth it in my opinion.

Just to put it out there (although it may have come up out-of-band), but I believe the idea is that this feature would allow MultiROM to be the foundation for a [mobile version of Tails OS](http://www.dailydot.com/technology/tor-anonymous-os-tails-freitas/). It's definitely the most interesting candidate out there

**Comment by Zaxscdvf** [comment]
a rom that I am excited about is guardian rom http://www.guardianrom.com/

**Comment by patcon** [comment]
Me too :)

**Comment by Tasssadar** [comment]
MultiROM supports encryption since v32 on nexus 7 (2012 & 2013), Nexus 5 and Nexus 6 only.

However, the moment you unlock your bootloader, install custom recovery and/or root the phone, the security is obviously broken, since anybody can install modified version of MultiROM or TWRP that records your password. I added the support because shamu is encrypted by default, and I wanted MultiROM to work with that.

**Comment by berryman13** [comment]
How about people with devices like myself, the LG G2, which requires loki and or bump signing to even boot

. Struggling to bring this up to lollipop, any advice advice for devices which need additional signing
