### ISSUE TITLE
Nethunter file is to big

### ISSUE THREAD

**Issue by Zaxscdvf** [Tasssadar/multirom#39]
the nethunter image is about a 1GB and when i try to install it  multirom cuts it half due to it being to big and the installation fails, is there a way to fix this. As well i noticed some roms dont work and some do for example i can install AOKP but not slimrom.

**Comment by Tasssadar** [comment]
Nethunter needs to be installed over 4.4.4 ROM - you use 4.4.4 ZIP to "add rom" to multirom and then flash the nethunter ZIP into it. You also need quite a bit of free space because of how nethunter installation works (and it won't tell you if it fails because it didn't have enough space).

Lots of ZIP compatibility were resolved by today's 2.8.4 update, if you still have some, reopen this issue.

**Comment by Zaxscdvf** [comment]
ok thanks but my nexus 5 only has 16GB and i have already used up half so i was thinking if i could install it on a usb, would that work?
